modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
iconFile="tm_wagon.png"
description='''Build modular wooden wagons, haul cargo, and travel with horse-drawn carts.'''

[[mixins]]
config="tm_wagon.mixins.json"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},26.3)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="geckolib"
type="required"
versionRange="${geckolib_version_range}"
ordering="NONE"
side="BOTH"
