modLoader="javafml"
loaderVersion="[47,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''Modular wooden wagons for travelling merchants. Forge 1.20.1 port in preparation.'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="geckolib"
mandatory=true
versionRange="${geckolib_version_range}"
ordering="AFTER"
side="BOTH"
