"""Generate the low-poly straw mat and a deterministic 64x64 dry-hay pixel texture."""
from pathlib import Path
import json
import random
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "src/main/resources/assets/tm_wagon"
rng = random.Random(317064)
palette = [(181, 151, 68), (197, 168, 79), (211, 183, 94), (224, 199, 117), (234, 210, 136), (162, 132, 58)]
texture = Image.new("RGB", (64, 64))
pixels = texture.load()
for y in range(64):
    for x in range(64):
        pixels[x, y] = palette[rng.choices(range(6), weights=[2, 4, 6, 3, 1, 1])[0]]
draw = ImageDraw.Draw(texture)
for _ in range(440):
    x, y = rng.randrange(64), rng.randrange(64)
    draw.line((x, y, x + rng.choice([-2, -1, 0, 1, 2]), y + rng.randrange(2, 9)), fill=rng.choice(palette), width=1)
for y in range(5, 64, 13):
    for x in range(64):
        if rng.random() < .8:
            pixels[x, y] = palette[0 if x % 3 else 5]
path = ASSETS / "textures/item/wagon_straw_mat.png"
path.parent.mkdir(parents=True, exist_ok=True)
texture.save(path)

def box(name, start, end, uv=None):
    return {"name": name, "from": start, "to": end,
            "faces": {face: {"texture": "#straw", "uv": uv or [0, 0, 16, 16]} for face in ["up", "down", "north", "south", "east", "west"]}}

model = {
    "credit": "TravelingMerchantWagon: dry straw mat, generated by tools/export_straw_mat.py",
    "textures": {"straw": "tm_wagon:item/wagon_straw_mat", "particle": "tm_wagon:item/wagon_straw_mat"},
    "elements": [
        box("woven_mat", [4.56, .016, -.32], [11.44, .44, 16.32]),
        box("left_binding", [4.56, .42, -.32], [4.84, .49, 16.32], [0, 0, 2, 16]),
        box("right_binding", [11.16, .42, -.32], [11.44, .49, 16.32], [0, 0, 2, 16]),
        box("rolled_headrest", [4.78, .42, -.2], [11.22, .98, 1.15], [0, 0, 16, 4]),
        box("lower_headrest", [4.84, .96, .02], [11.16, 1.0, .92], [0, 0, 16, 3]),
    ],
    "display": {
        "gui": {"rotation": [38, 35, 0], "translation": [0, 4, 0], "scale": [.68, .68, .68]},
        "ground": {"translation": [0, 3, 0], "scale": [.5, .5, .5]},
        "fixed": {"rotation": [90, 0, 0], "scale": [.75, .75, .75]},
        "thirdperson_righthand": {"rotation": [70, 0, 0], "translation": [0, 4, 1], "scale": [.4, .4, .4]},
        "thirdperson_lefthand": {"rotation": [70, 0, 0], "translation": [0, 4, 1], "scale": [.4, .4, .4]},
        "firstperson_righthand": {"rotation": [0, -30, 12], "translation": [0, 5, 0], "scale": [.5, .5, .5]},
        "firstperson_lefthand": {"rotation": [0, 30, -12], "translation": [0, 5, 0], "scale": [.5, .5, .5]},
    },
}
path = ASSETS / "models/item/wagon_straw_mat.json"
path.write_text(json.dumps(model, indent=2) + "\n", encoding="utf-8")
print("Exported straw mat item model (5 cuboids) and 64x64 texture.")
